# Generated by Django 5.2 on 2025-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
