# Generated by Django 5.2 on 2025-05-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_github_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github_username',
        ),
    ]
